set_property SRC_FILE_INFO {cfile:/root/Development/microblaze_uart/microblaze_uart.srcs/constrs_1/new/constraints.xdc rfile:../../../microblaze_uart.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports UART_0_rxd]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports UART_0_txd]
